[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
# podstawowy zestaw
extend-select = ["E", "F", "I", "B", "UP"]
ignore = []

[tool.mypy]
python_version = "3.11"
# tryb przyjazny: nie przerywamy pracy na brakujących typach
ignore_missing_imports = true
disallow_untyped_defs = false
check_untyped_defs = false
no_implicit_optional = false
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = false
warn_unreachable = false
strict_optional = false
show_error_codes = true
pretty = true
namespace_packages = true
exclude = '(?x)^(memory\.py|psychika\.py)$'
